server:
  port: 9201
spring:
  application:
    name: tensquare-base

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMillisecond: 70000 # 熔断超时时长：10000ms
ribbon:
  eurake:
    enabled: true
  ConnecctTimeout: 5000
  ReadTimeout: 5000
logging:


